Repository CS2113-AY1819S1-W13-3/main, pull requests merged in 2018-10, with the labels that each got.

#23 Added Deadline Class + SelectDeadline
  LICENSE
  docs/DeveloperGuide.adoc
  docs/templates/LICENSE
  src/main/java/seedu/address/logic/commands/SelectDeadlineCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SelectDeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/exceptions/InvalidDeadlineException.java
  src/test/java/seedu/address/logic/commands/SelectDeadlineCommandTest.java
  src/test/java/seedu/address/testutil/DeadlineBuilder.java
Labels: priority.high, status.ongoing

#20 Added Milestone class and AddMilestoneCommand feature
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddMilestoneCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Milestone.java
Labels: priority.high

#53 Bugs and updating of docs
  .travis.yml
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/CompleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/XmlAdaptedTask.java
  src/main/java/seedu/address/storage/XmlSerializableTaskBook.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/CommandHistoryTest.java
  src/test/java/seedu/address/logic/ListElementPointerTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CompleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/TaskBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlAdaptedTaskTest.java
  src/test/java/seedu/address/storage/XmlSerializableTaskBookTest.java
  src/test/java/seedu/address/storage/XmlTaskBookStorageTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: severity.High, type.bug

#46 Sort Tasks
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/SortTaskCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SortTaskCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedTaskBook.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/task/PriorityLevel.java
  src/main/java/seedu/address/model/task/SortTaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/storage/XmlAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlSerializableTaskBookTest/duplicateTasksInTaskBook.xml
  src/test/data/XmlSerializableTaskBookTest/typicalTaskBook.xml
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CompleteTaskCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.medium
